Change bucket destination to be in line with standards, changed final.yml to contain versioned name for release readability
Smarsh/cf-kafka-boshrelease pull request #16
Opened 2020-06-22 19:45 UTC by dpmidd

2020-06-23 13:38 UTC, ChineduUzoka commented on ci/pipeline.yml
> +      repository: smarshsre/data-services-boshcli2
No issue with this obviously

2020-06-24 18:53 UTC, dpmidd commented
@ChineduUzoka Let's review this tomorrow in the pipeline sync up with Warness

2020-06-29 14:16 UTC, washkinazy requested changes

2020-06-29 14:16 UTC, washkinazy commented on ci/pipeline.yml
> +      regexp: sredataservices/kafka/kafka-2.4.2/0.1.0/((bosh-release-name))-(.*).tgz
What is `0.1.0`?

2020-07-06 19:33 UTC, closed without merging